
export const SET_USER_UNREAD_NOTIFICATIONS = 'User//SET_USER_UNREAD_NOTIFICATIONS'
export const INCREMENT_USER_UNREAD_NOTIFICATIONS = 'User//INCREMENT_USER_UNREAD_NOTIFICATIONS'
export const DECREMENT_USER_UNREAD_NOTIFICATIONS = 'User//DECREMENT_USER_UNREAD_NOTIFICATIONS'
